// Copyright 2026 AceMQ.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Holds this library to both columns of avro-resolution-fixtures.json.
//
// The rule the fixture pins is the same one in all five languages: a library
// resolves when it has a reader schema to resolve onto, and not otherwise. What
// differs is where a reader schema comes from. A Go struct carries none, so this
// library has one only when the caller passes [ReaderSchema] — which makes Go the
// one library whose two columns are both reachable through the same call, with
// one option added.
//
// So both are asserted here. Neither is a bug and neither is being changed: they
// are two answers to two different questions about the same bytes, and the point
// of the file is that the sentence saying so has bytes behind it.
//
// The bodies are Java's, decoded here rather than re-encoded. Encoding them
// again would only prove that this library agrees with itself.

package avro

import (
	"context"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"testing"

	"github.com/AceMQ-Company/acemq-go-amqp/patterns"
)

// The core module's testdata directory, which is where scripts/check-fixtures.sh
// looks for this library's copy. It is outside this module — the codec is a
// module of its own so the core keeps its single dependency — and the path walks
// out to it rather than the repository carrying two copies that can drift.
const resolutionFixturesPath = "../../internal/testdata/avro-resolution-fixtures.json"

type resolutionFixtures struct {
	GeneratedBy string `json:"generatedBy"`
	Libraries   []struct {
		Library string `json:"library"`
		Column  string `json:"column"`
		Why     string `json:"why"`
	} `json:"libraries"`
	Cases []resolutionCase `json:"cases"`
}

type resolutionCase struct {
	Case         string         `json:"case"`
	SchemaID     int            `json:"schemaId"`
	WriterSchema string         `json:"writerSchema"`
	ReaderSchema string         `json:"readerSchema"`
	BodyBase64   string         `json:"bodyBase64"`
	Resolved     map[string]any `json:"resolved"`
	WriterShape  map[string]any `json:"writerShape"`
}

func loadResolutionFixtures(t *testing.T) resolutionFixtures {
	t.Helper()

	raw, err := os.ReadFile(resolutionFixturesPath)
	if err != nil {
		t.Fatalf("the shared fixture is not where every library keeps it: %v", err)
	}
	var fixtures resolutionFixtures
	if err := json.Unmarshal(raw, &fixtures); err != nil {
		t.Fatalf("the shared fixture is not readable JSON: %v", err)
	}
	if fixtures.GeneratedBy != "acemq-java-amqp AvroResolutionFixtures" {
		t.Fatalf("this file was generated by %q, not the generator these tests were written against",
			fixtures.GeneratedBy)
	}
	return fixtures
}

func fixtureCase(t *testing.T, name string) resolutionCase {
	t.Helper()

	for _, entry := range loadResolutionFixtures(t).Cases {
		if entry.Case == name {
			return entry
		}
	}
	t.Fatalf("no case named %q in the avro resolution fixtures", name)
	return resolutionCase{}
}

// fixtureRegistry answers a lookup by identifier, and nothing else.
//
// [patterns.NewInMemorySchemaRegistry] hands out identifiers of its own, counting
// from one, so it cannot be made to answer for 101 and 102 — the identifiers the
// fixture's bodies carry in their frames. Those numbers are part of the fixture:
// the bytes name them, and a registry answering a different one would be an
// assertion against a body this file does not contain.
//
// Register refuses rather than inventing an identifier, so a test that encodes
// through one of these codecs by accident fails where it happens.
type fixtureRegistry map[int]string

func (r fixtureRegistry) Register(
	_ context.Context, subject, _, _ string,
) (patterns.SchemaDefinition, error) {
	return patterns.SchemaDefinition{}, fmt.Errorf(
		"acemq: the fixture registry only answers lookups, and %q was registered with it", subject)
}

func (r fixtureRegistry) ByID(_ context.Context, id int) (patterns.SchemaDefinition, error) {
	definition, present := r[id]
	if !present {
		return patterns.SchemaDefinition{}, fmt.Errorf("%w with id %d", patterns.ErrSchemaNotFound, id)
	}
	return patterns.SchemaDefinition{
		ID:         id,
		Subject:    "resolution.order",
		Version:    1,
		Format:     "avro",
		Definition: definition,
	}, nil
}

func (r fixtureRegistry) Latest(_ context.Context, subject string) (patterns.SchemaDefinition, error) {
	return patterns.SchemaDefinition{}, fmt.Errorf("%w for subject %q", patterns.ErrSchemaNotFound, subject)
}

func (r fixtureRegistry) Versions(_ context.Context, subject string) ([]patterns.SchemaDefinition, error) {
	return nil, fmt.Errorf("%w for subject %q", patterns.ErrSchemaNotFound, subject)
}

// decodeFixture decodes a case's body through a consumer holding its reader schema.
//
// The codec is built the same way for both columns — same registry, same subject,
// same schema — so the only thing that differs between a resolved read and a
// writer-shape one is the option passed in. Anything else would leave the two
// columns differing for some second reason as well.
func decodeFixture(t *testing.T, entry resolutionCase, options ...Option) map[string]any {
	t.Helper()

	body, err := base64.StdEncoding.DecodeString(entry.BodyBase64)
	if err != nil {
		t.Fatalf("the fixture body for %s is not base64: %v", entry.Case, err)
	}

	registry := fixtureRegistry{entry.SchemaID: entry.WriterSchema}
	codec, err := Registered(registry, "resolution.order", entry.ReaderSchema, options...)
	if err != nil {
		t.Fatal(err)
	}

	decoded := map[string]any{}
	if err := codec.Decode(body, &decoded); err != nil {
		t.Fatalf("decoding %s: %v", entry.Case, err)
	}
	return decoded
}

// assertColumn compares a decoded record with one of the fixture's two columns.
//
// The whole record, not the expected keys one at a time. The difference between
// the two columns in the first case is a field present in one and absent in the
// other, so a comparison that only walked the keys it expected would pass
// against either column: the shorter one would ignore the extra field, and the
// longer one is the one with the field in it.
//
// Both sides go through JSON first, which puts the keys in one order and the
// numbers in one type. The fixture's decoded forms are ordered as their schema
// declares them and a Go map is not ordered at all, which is the case the
// fixture's howToAssert names: compare as a map.
func assertColumn(t *testing.T, decoded, expected map[string]any, column string) {
	t.Helper()

	got, want := canonicalJSON(t, decoded), canonicalJSON(t, expected)
	if got != want {
		t.Errorf("the %s column is %s, and this decoded as %s", column, want, got)
	}
}

// canonicalJSON renders a record so two of them can be compared as strings:
// keys sorted, and every number the same type on both sides.
func canonicalJSON(t *testing.T, value map[string]any) string {
	t.Helper()

	raw, err := json.Marshal(value)
	if err != nil {
		t.Fatalf("cannot render %+v: %v", value, err)
	}
	var normalised map[string]any
	if err := json.Unmarshal(raw, &normalised); err != nil {
		t.Fatalf("cannot re-read %s: %v", raw, err)
	}
	canonical, err := json.Marshal(normalised)
	if err != nil {
		t.Fatalf("cannot render %s: %v", raw, err)
	}
	return string(canonical)
}

// TestTheFixtureStillSaysGoIsTheOptInOne. The column this library is asserted
// against is named in the file, not decided here, and a fixture that moved Go to
// another column would otherwise leave these tests quietly asserting the old one.
func TestTheFixtureStillSaysGoIsTheOptInOne(t *testing.T) {
	for _, library := range loadResolutionFixtures(t).Libraries {
		if library.Library != "acemq-go-amqp" {
			continue
		}
		if library.Column != "writerShape" {
			t.Fatalf("the fixture puts Go in the %q column, and these tests assert writerShape "+
				"by default and resolved on request", library.Column)
		}
		return
	}
	t.Fatal("the fixture does not name acemq-go-amqp at all")
}

// TestAReaderSchemaFillsInTheFieldTheWriterRemoved is the case that matters.
//
// The writer never sent currency and the reader declares it with a default of
// "GBP" — a value that appears in no message and in no writer schema, so it can
// only have come from the reader's declaration. A default that was also the zero
// value would pass whether resolution happened or not.
func TestAReaderSchemaFillsInTheFieldTheWriterRemoved(t *testing.T) {
	entry := fixtureCase(t, "field-removed-by-the-writer")

	decoded := decodeFixture(t, entry, ReaderSchema(entry.ReaderSchema))

	if decoded["currency"] != "GBP" {
		t.Errorf("currency is %v, and the reader schema defaults it to %q", decoded["currency"], "GBP")
	}
	assertColumn(t, decoded, entry.Resolved, "resolved")
}

// TestWithoutAReaderSchemaTheWritersShapeArrives is the same body and the same
// codec with one option missing, and it is the column this library lands on
// unless a caller asks otherwise: a Go struct carries no schema, so there is
// nothing to resolve onto.
func TestWithoutAReaderSchemaTheWritersShapeArrives(t *testing.T) {
	entry := fixtureCase(t, "field-removed-by-the-writer")

	decoded := decodeFixture(t, entry)

	// Not the zero value: absent. The writer's schema has never heard of the
	// field, and there is no second declaration saying what to put in it.
	if _, present := decoded["currency"]; present {
		t.Errorf("currency reached a reader that was never given a schema declaring it: %+v", decoded)
	}
	assertColumn(t, decoded, entry.WriterShape, "writerShape")
}

// TestAFieldTheWriterAddedIsHarmlessEitherWay is the direction everybody assumes
// is the dangerous one. It is skipped under resolution and carried without it,
// and either way the fields the reader does declare come back correct.
func TestAFieldTheWriterAddedIsHarmlessEitherWay(t *testing.T) {
	entry := fixtureCase(t, "field-added-by-the-writer")

	resolved := decodeFixture(t, entry, ReaderSchema(entry.ReaderSchema))
	writerShape := decodeFixture(t, entry)

	assertColumn(t, resolved, entry.Resolved, "resolved")
	assertColumn(t, writerShape, entry.WriterShape, "writerShape")

	// The property that matters, said once rather than inferred from the two
	// columns: the unknown field did not shift the fields in front of it. That
	// is the failure an added field is expected to cause and the reason it does
	// not happen.
	for _, field := range []string{"orderId", "total", "currency"} {
		if fmt.Sprint(resolved[field]) != fmt.Sprint(writerShape[field]) {
			t.Errorf("%s is %v resolved and %v as written", field, resolved[field], writerShape[field])
		}
	}
	if _, present := resolved["channel"]; present {
		t.Errorf("a field the reader does not declare survived resolution: %+v", resolved)
	}
}

// TestTheFramedIdentifierIsTheOneTheFixtureNames. The bodies are Confluent-framed
// and the identifier in the frame is what sends this library to the registry, so
// a body whose frame said something else would be looked up as another schema.
func TestTheFramedIdentifierIsTheOneTheFixtureNames(t *testing.T) {
	for _, entry := range loadResolutionFixtures(t).Cases {
		body, err := base64.StdEncoding.DecodeString(entry.BodyBase64)
		if err != nil {
			t.Fatalf("the fixture body for %s is not base64: %v", entry.Case, err)
		}
		if len(body) < frameSize || body[0] != magic {
			t.Fatalf("%s does not begin with the framing byte", entry.Case)
		}
		if id := int(binary.BigEndian.Uint32(body[1:frameSize])); id != entry.SchemaID {
			t.Errorf("%s frames schema %d, and the fixture says %d", entry.Case, id, entry.SchemaID)
		}
	}
}
