// Copyright 2026 AceMQ.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rabbitmq_test

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"os"
	"strings"
	"testing"
	"time"

	acemq "github.com/AceMQ-Company/acemq-go-amqp/amqp"
	"github.com/AceMQ-Company/acemq-go-amqp/security"
)

// These tests need a broker listening for TLS with an AceMQ development
// certificate, which is what the tooling generates:
//
//	ACEMQ_TEST_AMQPS_URL=amqps://guest:guest@localhost:5671/ \
//	ACEMQ_TEST_CA=certs/ca.crt \
//	go test ./rabbitmq/
//
// They prove the things unit tests with an in-process listener cannot: that a
// real broker's chain verifies against the configured authority, and that the
// development marker is found on a certificate somebody else generated.
func tlsBroker(t *testing.T) (url, ca string) {
	t.Helper()
	url = os.Getenv("ACEMQ_TEST_AMQPS_URL")
	ca = os.Getenv("ACEMQ_TEST_CA")
	if url == "" || ca == "" {
		t.Skip("ACEMQ_TEST_AMQPS_URL and ACEMQ_TEST_CA are not both set; skipping the TLS tests")
	}
	return url, ca
}

func connectTLS(t *testing.T, sec *security.Options) error {
	t.Helper()
	url, _ := tlsBroker(t)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	mq, err := acemq.Connect(ctx, url, acemq.WithSecurity(sec))
	if err != nil {
		return err
	}
	t.Cleanup(func() { _ = mq.Close() })
	return nil
}

// TestARealDevelopmentBrokerIsRefusedByDefault is the one worth having a broker
// for.
//
// The certificate was generated by the AceMQ tooling and carries the marker in
// its organisation name. Nothing about this configuration is otherwise wrong —
// the authority is trusted, the host matches, the chain is valid — and it is
// still refused, because a development certificate reaching a production
// configuration should be an error rather than a thing that works.
func TestARealDevelopmentBrokerIsRefusedByDefault(t *testing.T) {
	_, ca := tlsBroker(t)

	err := connectTLS(t, security.Required().TrustCertificateAuthorityFile(ca))

	if err == nil {
		t.Fatal("a development certificate was accepted against a real broker")
	}
	if !strings.Contains(err.Error(), security.DevelopmentMarker) {
		t.Errorf("refused, but not for the reason under test: %v", err)
	}
	if !strings.Contains(err.Error(), "AllowDevelopmentCertificates") {
		t.Errorf("the error does not say how to permit it deliberately: %v", err)
	}
}

func TestARealDevelopmentBrokerConnectsWhenAllowed(t *testing.T) {
	_, ca := tlsBroker(t)

	err := connectTLS(t, security.Required().
		TrustCertificateAuthorityFile(ca).
		AllowDevelopmentCertificates())

	if err != nil {
		t.Fatalf("a development broker was refused despite being allowed: %v", err)
	}
}

func TestARealBrokerIsRefusedWhenTheAuthorityIsWrong(t *testing.T) {
	// A valid authority, but not this broker's. The handshake must fail even
	// with development certificates allowed, because trusting one authority has
	// to mean trusting one authority.
	other := t.TempDir() + "/other-ca.crt"
	writeUnrelatedAuthority(t, other)

	err := connectTLS(t, security.Required().
		TrustCertificateAuthorityFile(other).
		AllowDevelopmentCertificates())

	if err == nil {
		t.Fatal("the broker was accepted under an authority that did not sign it")
	}
}

func TestInsecureStillRefusesTheRealDevelopmentBroker(t *testing.T) {
	tlsBroker(t)

	err := connectTLS(t, security.Insecure())

	if err == nil {
		t.Fatal("Insecure accepted a development certificate against a real broker")
	}
	// The refusal has to be the marker rather than anything else. An earlier
	// version of this test passed against a broker whose password was wrong,
	// which proved nothing at all about the certificate.
	if !strings.Contains(err.Error(), security.DevelopmentMarker) {
		t.Errorf("refused, but not for the reason under test: %v", err)
	}
}

func TestInsecureConnectsToTheRealBrokerWhenDevelopmentIsAllowed(t *testing.T) {
	tlsBroker(t)

	err := connectTLS(t, security.Insecure().AllowDevelopmentCertificates())

	if err != nil {
		t.Fatalf("Insecure refused a broker it should have accepted: %v", err)
	}
}

func TestAskingForTlsOnAPlaintextUrlIsRefused(t *testing.T) {
	// The quietest possible failure: TLS configured, amqp:// in the URL, and a
	// plaintext connection with no warning. It is caught before the socket is
	// opened rather than being discovered later.
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, err := acemq.Connect(ctx, "amqp://guest:guest@localhost:5671/",
		acemq.WithSecurity(security.Required()))

	if err == nil {
		t.Fatal("TLS was configured against an amqp:// URL and the connection went ahead")
	}
	if !strings.Contains(err.Error(), "plaintext") {
		t.Errorf("the error does not explain the mismatch: %v", err)
	}
}

func TestDisablingSecurityOnAnAmqpsUrlIsRefused(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, err := acemq.Connect(ctx, "amqps://guest:guest@localhost:5671/",
		acemq.WithSecurity(security.Disabled()))

	if err == nil {
		t.Fatal("security was disabled against an amqps:// URL and the connection went ahead")
	}
}

func TestCredentialsFromTheProviderReachTheBroker(t *testing.T) {
	url, ca := tlsBroker(t)

	// The URL deliberately carries a password that would not work, to prove the
	// provider's credentials are the ones used rather than a fallback.
	withBadPassword := strings.Replace(url, "guest:guest@", "guest:definitely-wrong@", 1)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	mq, err := acemq.Connect(ctx, withBadPassword, acemq.WithSecurity(
		security.Required().
			TrustCertificateAuthorityFile(ca).
			AllowDevelopmentCertificates().
			WithCredentials(security.StaticCredentials("guest", "guest"))))
	if err != nil {
		t.Fatalf("the provider's credentials did not replace the URL's: %v", err)
	}
	_ = mq.Close()
}

func TestBadCredentialsAreReportedRatherThanHanging(t *testing.T) {
	url, ca := tlsBroker(t)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	_, err := acemq.Connect(ctx, url, acemq.WithSecurity(
		security.Required().
			TrustCertificateAuthorityFile(ca).
			AllowDevelopmentCertificates().
			WithCredentials(security.StaticCredentials("guest", "definitely-wrong"))))

	if err == nil {
		t.Fatal("a wrong password connected")
	}
	if strings.Contains(err.Error(), "definitely-wrong") {
		t.Errorf("the password appears in the error, so it will appear in logs: %v", err)
	}
}

// writeUnrelatedAuthority puts a valid but unrelated certificate authority on
// disk, so a test can prove the broker is refused under it.
func writeUnrelatedAuthority(t *testing.T, path string) {
	t.Helper()

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber:          big.NewInt(time.Now().UnixNano()),
		Subject:               pkix.Name{CommonName: "An Unrelated CA"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	encoded := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	if err := os.WriteFile(path, encoded, 0o600); err != nil {
		t.Fatal(err)
	}
}
