// Copyright 2026 AceMQ.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package acemq

import (
	"context"
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"sync"
	"testing"
	"time"
)

type fixtureFile struct {
	GeneratedBy string        `json:"generatedBy"`
	Contract    string        `json:"contract"`
	Cases       []fixtureCase `json:"cases"`
}

type fixtureCase struct {
	Case        string         `json:"case"`
	RoutingKey  string         `json:"routingKey"`
	MessageID   string         `json:"messageId"`
	Body        string         `json:"body"`
	ContentType string         `json:"contentType"`
	Headers     map[string]any `json:"headers"`
}

func loadFixtures(t *testing.T) fixtureFile {
	t.Helper()
	raw, err := os.ReadFile("../internal/testdata/envelope-fixtures.json")
	if err != nil {
		t.Fatalf("cannot read the fixtures: %v", err)
	}
	var f fixtureFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("cannot parse the fixtures: %v", err)
	}
	if len(f.Cases) == 0 {
		t.Fatal("the fixtures are empty, so this test proves nothing")
	}
	return f
}

// normalise makes two header maps comparable.
//
// JSON has one number type and AMQP has several, so a value that is an int here
// arrives from the fixture file as a float64. Comparing without this would fail
// on the encoding of the comparison rather than on the contract being tested.
func normalise(h map[string]any) map[string]any {
	out := make(map[string]any, len(h))
	for k, v := range h {
		switch n := v.(type) {
		case float64:
			out[k] = int64(n)
		case float32:
			out[k] = int64(n)
		case int:
			out[k] = int64(n)
		case int32:
			out[k] = int64(n)
		case int64:
			out[k] = n
		case []byte:
			out[k] = string(n)
		default:
			out[k] = v
		}
	}
	return out
}

// TestFixturesSurviveTheRoundTrip is the test that keeps the three libraries
// speaking the same language. The fixtures were generated by the Java
// implementation, so reading one and writing it back has to produce exactly
// what Java produced — no header gained, none lost, none renamed.
func TestFixturesSurviveTheRoundTrip(t *testing.T) {
	f := loadFixtures(t)

	for _, c := range f.Cases {
		t.Run(c.Case, func(t *testing.T) {
			env := EnvelopeFromWire(c.Headers, c.RoutingKey, c.MessageID)
			got := normalise(env.ToWire())
			want := normalise(c.Headers)

			if !reflect.DeepEqual(got, want) {
				for k, w := range want {
					if g, ok := got[k]; !ok {
						t.Errorf("header %q was lost: Java wrote %v (%T)", k, w, w)
					} else if !reflect.DeepEqual(g, w) {
						t.Errorf("header %q: Java wrote %v (%T), this wrote %v (%T)", k, w, w, g, g)
					}
				}
				for k, g := range got {
					if _, ok := want[k]; !ok {
						t.Errorf("header %q was invented: this wrote %v (%T), Java wrote nothing", k, g, g)
					}
				}
			}
		})
	}
}

func TestFixturesDecodeToTheExpectedFields(t *testing.T) {
	f := loadFixtures(t)

	for _, c := range f.Cases {
		t.Run(c.Case, func(t *testing.T) {
			env := EnvelopeFromWire(c.Headers, c.RoutingKey, c.MessageID)

			if want := c.Headers[HeaderID]; env.ID != want {
				t.Errorf("ID = %q, want %v", env.ID, want)
			}
			if want := c.Headers[HeaderType]; env.Type != want {
				t.Errorf("Type = %q, want %v", env.Type, want)
			}
			if env.Attempt < 1 {
				t.Errorf("Attempt = %d, which is never valid", env.Attempt)
			}
			if env.FirstSeen.IsZero() {
				t.Error("FirstSeen was not read")
			}
			// The application never sees the engine's headers, whatever they say.
			for k := range env.Headers {
				if IsAceHeader(k) {
					t.Errorf("reserved header %q reached the application", k)
				}
			}
		})
	}
}

func TestApplicationHeadersSurviveButReservedOnesDoNot(t *testing.T) {
	wire := map[string]any{
		HeaderID:          "m-1",
		HeaderType:        "order.placed",
		"x-tenant":        "acme",
		"x-acemq-unknown": "from a newer version",
	}

	env := EnvelopeFromWire(wire, "orders", "")

	if env.Headers["x-tenant"] != "acme" {
		t.Errorf("the application's own header was dropped: %v", env.Headers)
	}
	if _, present := env.Headers["x-acemq-unknown"]; present {
		// Reserved means reserved even when this version has never heard of it.
		// Passing it through would let a header this library does not understand
		// look like one the application set.
		t.Error("an unrecognised reserved header reached the application")
	}
}

func TestTheDefaultsAreTheOnesJavaApplies(t *testing.T) {
	env, err := NewEnvelope("order.placed")
	if err != nil {
		t.Fatal(err)
	}

	if env.ID == "" {
		t.Error("no id was generated")
	}
	if env.CorrelationID != env.ID {
		t.Errorf("CorrelationID = %q, want it to fall back to the id %q", env.CorrelationID, env.ID)
	}
	if env.Version != 1 {
		t.Errorf("Version = %d, want 1", env.Version)
	}
	if env.Attempt != 1 {
		t.Errorf("Attempt = %d, want 1", env.Attempt)
	}
	if !strings.HasPrefix(env.Origin, "acemq@") {
		t.Errorf("Origin = %q, want it to start with acemq@", env.Origin)
	}
	if env.FirstSeen.IsZero() {
		t.Error("FirstSeen was not set")
	}
}

func TestAnAbsentValueIsAnAbsentHeaderRatherThanANullOne(t *testing.T) {
	env, err := NewEnvelope("order.placed")
	if err != nil {
		t.Fatal(err)
	}
	wire := env.ToWire()

	// Java omits these entirely rather than writing a null, and a message that
	// carries a null where Java carries nothing is a different message.
	for _, absent := range []string{HeaderCausation, HeaderError, HeaderClaim} {
		if _, present := wire[absent]; present {
			t.Errorf("%q was written for an envelope that has none", absent)
		}
	}
}

func TestAReservedHeaderIsRefusedRatherThanSilentlyDropped(t *testing.T) {
	_, err := NewEnvelope("order.placed", Header("x-acemq-id", "mine"))
	if err == nil {
		t.Fatal("a reserved header name was accepted; it would be dropped on consume")
	}
	if !strings.Contains(err.Error(), "x-yourcompany-") {
		t.Errorf("the error does not say what to do instead: %v", err)
	}
}

func TestTypeAndCorrelationFallBackTheWayTheContractSays(t *testing.T) {
	env := EnvelopeFromWire(map[string]any{HeaderID: "m-1"}, "orders.created", "")

	if env.Type != "orders.created" {
		t.Errorf("Type = %q, want the routing key when the header is absent", env.Type)
	}
	if env.CorrelationID != "m-1" {
		t.Errorf("CorrelationID = %q, want the id when the header is absent", env.CorrelationID)
	}
}

func TestHeaderValuesAreReadWhicheverShapeTheBrokerUsed(t *testing.T) {
	// Clients differ on whether a long string arrives as a string or as bytes,
	// and on the width of an integer. All of it has to read the same.
	wire := map[string]any{
		HeaderID:        []byte("m-1"),
		HeaderAttempt:   int32(4),
		HeaderVersion:   "7",
		HeaderFirstSeen: float64(1767323045678),
	}

	env := EnvelopeFromWire(wire, "orders", "")

	if env.ID != "m-1" {
		t.Errorf("ID = %q, want m-1 read from bytes", env.ID)
	}
	if env.Attempt != 4 {
		t.Errorf("Attempt = %d, want 4 read from an int32", env.Attempt)
	}
	if env.Version != 7 {
		t.Errorf("Version = %d, want 7 read from a string", env.Version)
	}
	if got := env.FirstSeen.UnixMilli(); got != 1767323045678 {
		t.Errorf("FirstSeen = %d, want it read from a float", got)
	}
}

func TestNextAttemptDoesNotDisturbTheOriginal(t *testing.T) {
	env, err := NewEnvelope("order.placed", FirstSeen(time.Now().Add(-time.Minute)))
	if err != nil {
		t.Fatal(err)
	}

	next := env.NextAttempt()

	if env.Attempt != 1 {
		t.Errorf("the original was modified: Attempt = %d", env.Attempt)
	}
	if next.Attempt != 2 {
		t.Errorf("Attempt = %d, want 2", next.Attempt)
	}
	if next.ID != env.ID {
		t.Error("the identity changed, which would break idempotency")
	}
}

func TestIdsAreUniqueAndShaped(t *testing.T) {
	seen := map[string]bool{}
	for range 1000 {
		id := newID()
		if seen[id] {
			t.Fatalf("a message id repeated: %s", id)
		}
		seen[id] = true
		if len(id) != 36 || id[8] != '-' || id[14] != '4' {
			t.Fatalf("%q is not a version 4 UUID", id)
		}
	}
}

// TestAClaimSurvivesTheRoundTrip is the field this library reserved a header for
// and then never materialised.
//
// x-acemq- is the engine's namespace: a header in it that the engine does not
// put on the envelope is dropped before a handler sees it. So a name that is
// reserved and unmaterialised is the worst of both — it looks supported, it
// reaches the wire, and it vanishes.
func TestAClaimSurvivesTheRoundTrip(t *testing.T) {
	env, err := NewEnvelope("order.placed", Claim("s3://payloads/2026/09/order-1"))
	if err != nil {
		t.Fatal(err)
	}
	if env.Claim != "s3://payloads/2026/09/order-1" {
		t.Fatalf("Claim = %q", env.Claim)
	}

	wire := env.ToWire()
	if wire[HeaderClaim] != "s3://payloads/2026/09/order-1" {
		t.Fatalf("%s = %v on the wire", HeaderClaim, wire[HeaderClaim])
	}

	back := EnvelopeFromWire(wire, "orders", "")
	if back.Claim != env.Claim {
		t.Errorf("the claim came back as %q, want %q", back.Claim, env.Claim)
	}

	// And it is the engine's, so it does not also turn up among the
	// application's headers.
	if _, present := back.Headers[HeaderClaim]; present {
		t.Errorf("%s reached the application's headers as well", HeaderClaim)
	}
}

// TestAClaimFromAnotherLanguageReachesAGoHandler is the reason to materialise it
// rather than leave the constant sitting there.
//
// Python's Envelope.claim and Ruby's :claim are first-class fields that write
// this header. Before it was a field here, a message published by either of them
// arrived, was recognised as reserved, and had its claim dropped on the way to
// the handler.
func TestAClaimFromAnotherLanguageReachesAGoHandler(t *testing.T) {
	// The shape a Python or Ruby publisher puts on the wire. A long string can
	// arrive as bytes depending on the client, like every other header.
	fromElsewhere := map[string]any{
		HeaderID:    "order-1",
		HeaderType:  "order.placed",
		HeaderClaim: []byte("gs://payloads/order-1.json"),
	}

	env := EnvelopeFromWire(fromElsewhere, "orders", "")
	if env.Claim != "gs://payloads/order-1.json" {
		t.Errorf("a claim from another library reached the handler as %q", env.Claim)
	}
}

// TestAMessageWithNoClaimIsUnchanged, because materialising a field must not
// start writing a header onto every message the family exchanges. An absent
// value is an absent header, never an empty one.
func TestAMessageWithNoClaimIsUnchanged(t *testing.T) {
	env, err := NewEnvelope("order.placed")
	if err != nil {
		t.Fatal(err)
	}
	if env.Claim != "" {
		t.Errorf("a message nobody set a claim on has %q", env.Claim)
	}
	if _, present := env.ToWire()[HeaderClaim]; present {
		t.Errorf("%s was written for a message with no claim", HeaderClaim)
	}

	back := EnvelopeFromWire(env.ToWire(), "orders", "")
	if back.Claim != "" {
		t.Errorf("a message with no claim came back with %q", back.Claim)
	}
}

// TestAPublishedClaimReachesTheHandler is the round trip through the library
// rather than through the two envelope functions: publish with a claim, consume,
// and read it off the envelope the handler is given.
func TestAPublishedClaimReachesTheHandler(t *testing.T) {
	mq := brokerFor(t)
	declare(t, mq, "orders")

	var seen string
	var got atomicFlag

	consumer, err := Consume(context.Background(), mq, "orders",
		func(_ context.Context, m Message[OrderPlaced]) Ack {
			seen = m.Envelope.Claim
			got.set()
			return Accept()
		})
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = consumer.Close() }()

	pub := NewPublisher[OrderPlaced](mq, "", "orders")
	err = pub.Send(context.Background(), OrderPlaced{OrderID: "order-1"},
		Claim("s3://payloads/2026/09/order-1"))
	if err != nil {
		t.Fatal(err)
	}

	waitFor(t, "the message to be handled", got.isSet)
	if seen != "s3://payloads/2026/09/order-1" {
		t.Errorf("the handler saw a claim of %q", seen)
	}
}

// atomicFlag is a one-way flag a handler can set and a test can poll.
type atomicFlag struct {
	mu   sync.Mutex
	set_ bool
}

func (f *atomicFlag) set() {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.set_ = true
}

func (f *atomicFlag) isSet() bool {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.set_
}
